import { Helmet } from "react-helmet-async";

export type SEOProps = {
  title?: string;
  description?: string;
  image?: string;
  url?: string;
  keywords?: string[];
};
export const SEO = ({ title, image }: SEOProps) => {
  return (
    <Helmet>
      <title> {title ? `Bot builder | ${title}` : "Bot Builder"}</title>
      <meta content="Generated by create next app" name="description" />
      <link href={image ?? "/src/favicon.svg"} rel="icon" />
    </Helmet>
  );
};
